# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketIOSwift' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SocketIOSwift
  #pod 'Socket.IO-Client-Swift'

  target 'SocketIOSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocketIOSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
